// Code generated by protoc-gen-go. DO NOT EDIT.
// source: serviced.proto

package serviced

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Hash struct {
	Values               []uint32 `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	Data                 string   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Distance             uint32   `protobuf:"varint,3,opt,name=distance,proto3" json:"distance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hash) Reset()         { *m = Hash{} }
func (m *Hash) String() string { return proto.CompactTextString(m) }
func (*Hash) ProtoMessage()    {}
func (*Hash) Descriptor() ([]byte, []int) {
	return fileDescriptor_596b3664ace45541, []int{0}
}

func (m *Hash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hash.Unmarshal(m, b)
}
func (m *Hash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hash.Marshal(b, m, deterministic)
}
func (m *Hash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hash.Merge(m, src)
}
func (m *Hash) XXX_Size() int {
	return xxx_messageInfo_Hash.Size(m)
}
func (m *Hash) XXX_DiscardUnknown() {
	xxx_messageInfo_Hash.DiscardUnknown(m)
}

var xxx_messageInfo_Hash proto.InternalMessageInfo

func (m *Hash) GetValues() []uint32 {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *Hash) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Hash) GetDistance() uint32 {
	if m != nil {
		return m.Distance
	}
	return 0
}

type RequestSearch struct {
	Hash                 *Hash    `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Limit                uint32   `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestSearch) Reset()         { *m = RequestSearch{} }
func (m *RequestSearch) String() string { return proto.CompactTextString(m) }
func (*RequestSearch) ProtoMessage()    {}
func (*RequestSearch) Descriptor() ([]byte, []int) {
	return fileDescriptor_596b3664ace45541, []int{1}
}

func (m *RequestSearch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestSearch.Unmarshal(m, b)
}
func (m *RequestSearch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestSearch.Marshal(b, m, deterministic)
}
func (m *RequestSearch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestSearch.Merge(m, src)
}
func (m *RequestSearch) XXX_Size() int {
	return xxx_messageInfo_RequestSearch.Size(m)
}
func (m *RequestSearch) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestSearch.DiscardUnknown(m)
}

var xxx_messageInfo_RequestSearch proto.InternalMessageInfo

func (m *RequestSearch) GetHash() *Hash {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *RequestSearch) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type ResponseSearch struct {
	Hashes               []*Hash  `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseSearch) Reset()         { *m = ResponseSearch{} }
func (m *ResponseSearch) String() string { return proto.CompactTextString(m) }
func (*ResponseSearch) ProtoMessage()    {}
func (*ResponseSearch) Descriptor() ([]byte, []int) {
	return fileDescriptor_596b3664ace45541, []int{2}
}

func (m *ResponseSearch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseSearch.Unmarshal(m, b)
}
func (m *ResponseSearch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseSearch.Marshal(b, m, deterministic)
}
func (m *ResponseSearch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseSearch.Merge(m, src)
}
func (m *ResponseSearch) XXX_Size() int {
	return xxx_messageInfo_ResponseSearch.Size(m)
}
func (m *ResponseSearch) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseSearch.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseSearch proto.InternalMessageInfo

func (m *ResponseSearch) GetHashes() []*Hash {
	if m != nil {
		return m.Hashes
	}
	return nil
}

type RequestStats struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestStats) Reset()         { *m = RequestStats{} }
func (m *RequestStats) String() string { return proto.CompactTextString(m) }
func (*RequestStats) ProtoMessage()    {}
func (*RequestStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_596b3664ace45541, []int{3}
}

func (m *RequestStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestStats.Unmarshal(m, b)
}
func (m *RequestStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestStats.Marshal(b, m, deterministic)
}
func (m *RequestStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestStats.Merge(m, src)
}
func (m *RequestStats) XXX_Size() int {
	return xxx_messageInfo_RequestStats.Size(m)
}
func (m *RequestStats) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestStats.DiscardUnknown(m)
}

var xxx_messageInfo_RequestStats proto.InternalMessageInfo

type ResponseStats struct {
	LastUpdateTs         uint64   `protobuf:"varint,1,opt,name=last_update_ts,json=lastUpdateTs,proto3" json:"last_update_ts,omitempty"`
	TotalSearches        uint64   `protobuf:"varint,2,opt,name=total_searches,json=totalSearches,proto3" json:"total_searches,omitempty"`
	TotalNegative        uint64   `protobuf:"varint,3,opt,name=total_negative,json=totalNegative,proto3" json:"total_negative,omitempty"`
	TotalPositive        uint64   `protobuf:"varint,4,opt,name=total_positive,json=totalPositive,proto3" json:"total_positive,omitempty"`
	TotalHashes          uint64   `protobuf:"varint,5,opt,name=total_hashes,json=totalHashes,proto3" json:"total_hashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseStats) Reset()         { *m = ResponseStats{} }
func (m *ResponseStats) String() string { return proto.CompactTextString(m) }
func (*ResponseStats) ProtoMessage()    {}
func (*ResponseStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_596b3664ace45541, []int{4}
}

func (m *ResponseStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseStats.Unmarshal(m, b)
}
func (m *ResponseStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseStats.Marshal(b, m, deterministic)
}
func (m *ResponseStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseStats.Merge(m, src)
}
func (m *ResponseStats) XXX_Size() int {
	return xxx_messageInfo_ResponseStats.Size(m)
}
func (m *ResponseStats) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseStats.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseStats proto.InternalMessageInfo

func (m *ResponseStats) GetLastUpdateTs() uint64 {
	if m != nil {
		return m.LastUpdateTs
	}
	return 0
}

func (m *ResponseStats) GetTotalSearches() uint64 {
	if m != nil {
		return m.TotalSearches
	}
	return 0
}

func (m *ResponseStats) GetTotalNegative() uint64 {
	if m != nil {
		return m.TotalNegative
	}
	return 0
}

func (m *ResponseStats) GetTotalPositive() uint64 {
	if m != nil {
		return m.TotalPositive
	}
	return 0
}

func (m *ResponseStats) GetTotalHashes() uint64 {
	if m != nil {
		return m.TotalHashes
	}
	return 0
}

func init() {
	proto.RegisterType((*Hash)(nil), "serviced.Hash")
	proto.RegisterType((*RequestSearch)(nil), "serviced.RequestSearch")
	proto.RegisterType((*ResponseSearch)(nil), "serviced.ResponseSearch")
	proto.RegisterType((*RequestStats)(nil), "serviced.RequestStats")
	proto.RegisterType((*ResponseStats)(nil), "serviced.ResponseStats")
}

func init() { proto.RegisterFile("serviced.proto", fileDescriptor_596b3664ace45541) }

var fileDescriptor_596b3664ace45541 = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x4f, 0x4f, 0xf2, 0x40,
	0x10, 0xc6, 0x59, 0x28, 0x0d, 0xef, 0x40, 0x7b, 0xd8, 0xbc, 0x81, 0x86, 0x53, 0xdd, 0xa8, 0xe9,
	0x89, 0x03, 0x5e, 0x8c, 0x89, 0x17, 0x4f, 0x78, 0x21, 0x66, 0xc1, 0x33, 0x59, 0xe9, 0xc6, 0x36,
	0xa9, 0xb4, 0x32, 0x03, 0x77, 0x3f, 0xa0, 0xdf, 0xc9, 0x74, 0xba, 0xfc, 0x31, 0x78, 0xeb, 0xfc,
	0xe6, 0x99, 0x99, 0xa7, 0x4f, 0x16, 0x42, 0xb4, 0xdb, 0x7d, 0xbe, 0xb6, 0xe9, 0xa4, 0xda, 0x96,
	0x54, 0xca, 0xde, 0xa1, 0x56, 0x73, 0xf0, 0x66, 0x06, 0x33, 0x39, 0x04, 0x7f, 0x6f, 0x8a, 0x9d,
	0xc5, 0x48, 0xc4, 0x9d, 0x24, 0xd0, 0xae, 0x92, 0x12, 0xbc, 0xd4, 0x90, 0x89, 0xda, 0xb1, 0x48,
	0xfe, 0x69, 0xfe, 0x96, 0x63, 0xe8, 0xa5, 0x39, 0x92, 0xd9, 0xac, 0x6d, 0xd4, 0x89, 0x45, 0x12,
	0xe8, 0x63, 0xad, 0x9e, 0x21, 0xd0, 0xf6, 0x73, 0x67, 0x91, 0x16, 0xd6, 0x6c, 0xd7, 0x99, 0x54,
	0xe0, 0x65, 0x06, 0xb3, 0x48, 0xc4, 0x22, 0xe9, 0x4f, 0xc3, 0xc9, 0xd1, 0x49, 0x7d, 0x56, 0x73,
	0x4f, 0xfe, 0x87, 0x6e, 0x91, 0x7f, 0xe4, 0xc4, 0x57, 0x02, 0xdd, 0x14, 0xea, 0x1e, 0x42, 0x6d,
	0xb1, 0x2a, 0x37, 0x68, 0xdd, 0xae, 0x5b, 0xf0, 0x6b, 0xbd, 0x33, 0x79, 0xb9, 0xcd, 0x75, 0x55,
	0x08, 0x83, 0x83, 0x09, 0x32, 0x84, 0xea, 0x5b, 0xd4, 0xae, 0xdc, 0xaa, 0x9a, 0xc8, 0x6b, 0x08,
	0x0b, 0x83, 0xb4, 0xda, 0x55, 0xa9, 0x21, 0xbb, 0x22, 0x64, 0x7f, 0x9e, 0x1e, 0xd4, 0xf4, 0x95,
	0xe1, 0x12, 0xe5, 0x0d, 0x84, 0x54, 0x92, 0x29, 0x56, 0xc8, 0xf7, 0x2d, 0xb2, 0x41, 0x4f, 0x07,
	0x4c, 0x17, 0x0e, 0x9e, 0x64, 0x1b, 0xfb, 0x6e, 0x28, 0xdf, 0x37, 0xa9, 0x1c, 0x64, 0x73, 0x07,
	0x4f, 0xb2, 0xaa, 0xc4, 0x9c, 0x65, 0xde, 0x99, 0xec, 0xc5, 0x41, 0x79, 0x05, 0x83, 0x46, 0xe6,
	0x7e, 0xb5, 0xcb, 0xa2, 0x3e, 0xb3, 0x19, 0xa3, 0xe9, 0x97, 0x00, 0x6f, 0x69, 0x91, 0xe4, 0x23,
	0xf8, 0x2e, 0x9a, 0xd1, 0x29, 0x8a, 0x5f, 0xf9, 0x8f, 0xa3, 0xf3, 0xc6, 0x79, 0x9a, 0xaa, 0x25,
	0x1f, 0xa0, 0xdb, 0xc4, 0x31, 0xbc, 0x9c, 0xae, 0xf9, 0x78, 0xf4, 0xc7, 0x30, 0x27, 0xda, 0x7a,
	0x6a, 0xcf, 0xc4, 0x9b, 0xcf, 0xaf, 0xe9, 0xee, 0x27, 0x00, 0x00, 0xff, 0xff, 0x91, 0x11, 0x85,
	0x65, 0x5f, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TestClient is the client API for Test service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TestClient interface {
	Search(ctx context.Context, in *RequestSearch, opts ...grpc.CallOption) (*ResponseSearch, error)
	Stats(ctx context.Context, in *RequestStats, opts ...grpc.CallOption) (*ResponseStats, error)
}

type testClient struct {
	cc *grpc.ClientConn
}

func NewTestClient(cc *grpc.ClientConn) TestClient {
	return &testClient{cc}
}

func (c *testClient) Search(ctx context.Context, in *RequestSearch, opts ...grpc.CallOption) (*ResponseSearch, error) {
	out := new(ResponseSearch)
	err := c.cc.Invoke(ctx, "/serviced.Test/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testClient) Stats(ctx context.Context, in *RequestStats, opts ...grpc.CallOption) (*ResponseStats, error) {
	out := new(ResponseStats)
	err := c.cc.Invoke(ctx, "/serviced.Test/Stats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestServer is the server API for Test service.
type TestServer interface {
	Search(context.Context, *RequestSearch) (*ResponseSearch, error)
	Stats(context.Context, *RequestStats) (*ResponseStats, error)
}

// UnimplementedTestServer can be embedded to have forward compatible implementations.
type UnimplementedTestServer struct {
}

func (*UnimplementedTestServer) Search(ctx context.Context, req *RequestSearch) (*ResponseSearch, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (*UnimplementedTestServer) Stats(ctx context.Context, req *RequestStats) (*ResponseStats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stats not implemented")
}

func RegisterTestServer(s *grpc.Server, srv TestServer) {
	s.RegisterService(&_Test_serviceDesc, srv)
}

func _Test_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestSearch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serviced.Test/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServer).Search(ctx, req.(*RequestSearch))
	}
	return interceptor(ctx, in, info, handler)
}

func _Test_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestStats)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serviced.Test/Stats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServer).Stats(ctx, req.(*RequestStats))
	}
	return interceptor(ctx, in, info, handler)
}

var _Test_serviceDesc = grpc.ServiceDesc{
	ServiceName: "serviced.Test",
	HandlerType: (*TestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _Test_Search_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _Test_Stats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "serviced.proto",
}
